<?php
$img_dir = "images/headers/carousel";
$form = [];
$activities = [];
array_push($activities, ["name" =>  "reading"]);
array_push($activities, ["name" =>  "family-events", "label" => "Family Events"]);
array_push($activities, ["name" =>  "travel"]);
array_push($activities, ["name" =>  "galleries-museums", "label" => "Art Galleries / Musueums"]);
array_push($activities, ["name" =>  "exercise"]);
array_push($activities, ["name" =>  "eat"]);
array_push($activities, ["name" =>  "training-conferences", "label" => "Training / Conferences"]);
array_push($activities, ["name" =>  "meditation"]);
array_push($activities, ["name" =>  "socialising"]);
array_push($activities, ["name" =>  "family-time", "label" => "Spending Time With Family"]);
array_push($activities, ["name" =>  "yoga"]);
array_push($activities, ["name" =>  "work"]);
array_push($activities, ["name" =>  "other"]);
$form["activities"] = $activities;

$exercises = [];
array_push($exercises, ["name" =>  "running"]);
array_push($exercises, ["name" =>  "dance"]);
array_push($exercises, ["name" =>  "football"]);
array_push($exercises, ["name" =>  "swimming"]);
array_push($exercises, ["name" =>  "tennis"]);
array_push($exercises, ["name" =>  "gym"]);
array_push($exercises, ["name" =>  "yoga"]);
array_push($exercises, ["name" =>  "cycling"]);
array_push($exercises, ["name" =>  "golf"]);
array_push($exercises, ["name" =>  "rugby"]);
array_push($exercises, ["name" =>  "other"]);
$form["exercise"] = $exercises;

$time = [];
array_push($time, ["name" =>  "family"]);
array_push($time, ["name" =>  "exercise"]);
array_push($time, ["name" =>  "friends"]);
array_push($time, ["name" =>  "networking"]);
array_push($time, ["name" =>  "cooking"]);
array_push($time, ["name" =>  "kids"]);
array_push($time, ["name" =>  "socialising"]);
array_push($time, ["name" =>  "myself"]);
array_push($time, ["name" =>  "relaxing"]);
array_push($time, ["name" =>  "work"]);
array_push($time, ["name" =>  "self-development"]);
array_push($time, ["name" =>  "other"]);
$form["time"] = $time;

$surround = [];
array_push($surround, ["name" =>  "computer"]);
array_push($surround, ["name" =>  "childrens-toys", "label" => "Children's Toys"]);
array_push($surround, ["name" =>  "flowers"]);
array_push($surround, ["name" =>  "work"]);
array_push($surround, ["name" =>  "magazines"]);
array_push($surround, ["name" =>  "candles"]);
array_push($surround, ["name" =>  "phone"]);
array_push($surround, ["name" =>  "food"]);
array_push($surround, ["name" =>  "clothes-accessories", "label" => "Clothes / Accessories"]);
array_push($surround, ["name" =>  "books"]);
array_push($surround, ["name" =>  "family-photos", "label" => "Family Photos"]);
array_push($surround, ["name" =>  "exercise-equipment", "label" => "Exercise Equipment"]);
array_push($surround, ["name" =>  "other"]);
$form["surround"] = $surround;

$describe = [];
array_push($describe, ["name" =>  "driven"]);
array_push($describe, ["name" =>  "friendly"]);
array_push($describe, ["name" =>  "dependable"]);
array_push($describe, ["name" =>  "independent"]);
array_push($describe, ["name" =>  "optimistic"]);
array_push($describe, ["name" =>  "careful"]);
array_push($describe, ["name" =>  "competent"]);
array_push($describe, ["name" =>  "calm"]);
array_push($describe, ["name" =>  "diplomatic"]);
array_push($describe, ["name" =>  "warm"]);
array_push($describe, ["name" =>  "patient"]);
array_push($describe, ["name" =>  "tactful"]);
$form["describe"] = $describe;

$relax = [];
array_push($relax, ["name" =>  "reading"]);
array_push($relax, ["name" =>  "going-out", "label" => "Going Out"]);
array_push($relax, ["name" =>  "music-concerts", "label" => "Music / Concerts"]);
array_push($relax, ["name" =>  "relaxing-baths", "label" => "Relaxing Baths"]);
array_push($relax, ["name" =>  "socialising"]);
array_push($relax, ["name" =>  "theatres-galleries", "label" => "theatres / Galleries"]);
array_push($relax, ["name" =>  "meditation"]);
array_push($relax, ["name" =>  "cinema"]);
array_push($relax, ["name" =>  "nature-walks", "label" => "Nature Walks"]);
array_push($relax, ["name" =>  "facial-body-treatments", "label" => "Facial & Body Treatments"]);
array_push($relax, ["name" =>  "exercise"]);
array_push($relax, ["name" =>  "other"]);
$form["relax"] = $relax;

$community = [];
array_push($community, ["name" =>  "meeting-like-minded-people", "label" => "Meeting Like-Minded People"]);
array_push($community, ["name" =>  "self-development"]);
array_push($community, ["name" =>  "achieve-balanace", "label" => "Achieve Balance"]);
array_push($community, ["name" =>  "knowledge"]);
array_push($community, ["name" =>  "improve-confidence", "label" => "Improve Confidence"]);
array_push($community, ["name" =>  "socialising"]);
array_push($community, ["name" =>  "relaxation"]);
array_push($community, ["name" =>  "improve-self-love", "label" => "Imrove Self-love"]);
array_push($community, ["name" =>  "feel-beautiful", "label" => "Feel Beautiful"]);
array_push($community, ["name" =>  "time-for-myself", "label" => "Time For Myself"]);
array_push($community, ["name" =>  "time-to-think-or-stop-thinking", "label" => "Time To Think Or Stop Thinking"]);
array_push($community, ["name" =>  "other"]);
$form["community"] = $community;

$share = [];
array_push($share, ["name" =>  "travel"]);
array_push($share, ["name" =>  "nutrition"]);
array_push($share, ["name" =>  "cooking"]);
array_push($share, ["name" =>  "fitness"]);
array_push($share, ["name" =>  "socialising"]);
array_push($share, ["name" =>  "work"]);
array_push($share, ["name" =>  "reading"]);
array_push($share, ["name" =>  "spirituality"]);
array_push($share, ["name" =>  "music"]);
array_push($share, ["name" =>  "networking"]);
array_push($share, ["name" =>  "self-development"]);
array_push($share, ["name" =>  "networking"]);
array_push($share, ["name" =>  "other"]);
$form["share"] = $share;
?>
