<?php
$img_dir = "images/headers/carousel";
$form = array();
$activities = array();
array_push($activities, array("name" =>  "reading"));
array_push($activities, array("name" =>  "family-events", "label" => "Family Events"));
array_push($activities, array("name" =>  "travel"));
array_push($activities, array("name" =>  "galleries-museums", "label" => "Art Galleries / Musueums"));
array_push($activities, array("name" =>  "exercise"));
array_push($activities, array("name" =>  "eat"));
array_push($activities, array("name" =>  "training-conferences", "label" => "Training / Conferences"));
array_push($activities, array("name" =>  "meditation"));
array_push($activities, array("name" =>  "socialising"));
array_push($activities, array("name" =>  "family-time", "label" => "Spending Time With Family"));
array_push($activities, array("name" =>  "yoga"));
array_push($activities, array("name" =>  "work"));
array_push($activities, array("name" =>  "other"));
$form["activities"] = $activities;

$exercises = array();
array_push($exercises, array("name" =>  "running"));
array_push($exercises, array("name" =>  "dance"));
array_push($exercises, array("name" =>  "football"));
array_push($exercises, array("name" =>  "swimming"));
array_push($exercises, array("name" =>  "tennis"));
array_push($exercises, array("name" =>  "gym"));
array_push($exercises, array("name" =>  "yoga"));
array_push($exercises, array("name" =>  "cycling"));
array_push($exercises, array("name" =>  "golf"));
array_push($exercises, array("name" =>  "rugby"));
array_push($exercises, array("name" =>  "other"));
$form["exercise"] = $exercises;

$time = array();
array_push($time, array("name" =>  "family"));
array_push($time, array("name" =>  "exercise"));
array_push($time, array("name" =>  "friends"));
array_push($time, array("name" =>  "networking"));
array_push($time, array("name" =>  "cooking"));
array_push($time, array("name" =>  "kids"));
array_push($time, array("name" =>  "socialising"));
array_push($time, array("name" =>  "myself"));
array_push($time, array("name" =>  "relaxing"));
array_push($time, array("name" =>  "work"));
array_push($time, array("name" =>  "self-development"));
array_push($time, array("name" =>  "other"));
$form["time"] = $time;

$surround = array();
array_push($surround, array("name" =>  "computer"));
array_push($surround, array("name" =>  "childrens-toys", "label" => "Children's Toys"));
array_push($surround, array("name" =>  "flowers"));
array_push($surround, array("name" =>  "work"));
array_push($surround, array("name" =>  "magazines"));
array_push($surround, array("name" =>  "candles"));
array_push($surround, array("name" =>  "phone"));
array_push($surround, array("name" =>  "food"));
array_push($surround, array("name" =>  "clothes-accessories", "label" => "Clothes / Accessories"));
array_push($surround, array("name" =>  "books"));
array_push($surround, array("name" =>  "family-photos", "label" => "Family Photos"));
array_push($surround, array("name" =>  "exercise-equipment", "label" => "Exercise Equipment"));
array_push($surround, array("name" =>  "other"));
$form["surround"] = $surround;

$describe = array();
array_push($describe, array("name" =>  "driven"));
array_push($describe, array("name" =>  "friendly"));
array_push($describe, array("name" =>  "dependable"));
array_push($describe, array("name" =>  "independent"));
array_push($describe, array("name" =>  "optimistic"));
array_push($describe, array("name" =>  "careful"));
array_push($describe, array("name" =>  "competent"));
array_push($describe, array("name" =>  "calm"));
array_push($describe, array("name" =>  "diplomatic"));
array_push($describe, array("name" =>  "warm"));
array_push($describe, array("name" =>  "patient"));
array_push($describe, array("name" =>  "tactful"));
$form["describe"] = $describe;

$relax = array();
array_push($relax, array("name" =>  "reading"));
array_push($relax, array("name" =>  "going-out", "label" => "Going Out"));
array_push($relax, array("name" =>  "music-concerts", "label" => "Music / Concerts"));
array_push($relax, array("name" =>  "relaxing-baths", "label" => "Relaxing Baths"));
array_push($relax, array("name" =>  "socialising"));
array_push($relax, array("name" =>  "theatres-galleries", "label" => "theatres / Galleries"));
array_push($relax, array("name" =>  "meditation"));
array_push($relax, array("name" =>  "cinema"));
array_push($relax, array("name" =>  "nature-walks", "label" => "Nature Walks"));
array_push($relax, array("name" =>  "facial-body-treatments", "label" => "Facial & Body Treatments"));
array_push($relax, array("name" =>  "exercise"));
array_push($relax, array("name" =>  "other"));
$form["relax"] = $relax;

$community = array();
array_push($community, array("name" =>  "meeting-like-minded-people", "label" => "Meeting Like-Minded People"));
array_push($community, array("name" =>  "self-development"));
array_push($community, array("name" =>  "achieve-balanace", "label" => "Achieve Balance"));
array_push($community, array("name" =>  "knowledge"));
array_push($community, array("name" =>  "improve-confidence", "label" => "Improve Confidence"));
array_push($community, array("name" =>  "socialising"));
array_push($community, array("name" =>  "relaxation"));
array_push($community, array("name" =>  "improve-self-love", "label" => "Imrove Self-love"));
array_push($community, array("name" =>  "feel-beautiful", "label" => "Feel Beautiful"));
array_push($community, array("name" =>  "time-for-myself", "label" => "Time For Myself"));
array_push($community, array("name" =>  "time-to-think-or-stop-thinking", "label" => "Time To Think Or Stop Thinking"));
array_push($community, array("name" =>  "other"));
$form["community"] = $community;

$share = array();
array_push($share, array("name" =>  "travel"));
array_push($share, array("name" =>  "nutrition"));
array_push($share, array("name" =>  "cooking"));
array_push($share, array("name" =>  "fitness"));
array_push($share, array("name" =>  "socialising"));
array_push($share, array("name" =>  "work"));
array_push($share, array("name" =>  "reading"));
array_push($share, array("name" =>  "spirituality"));
array_push($share, array("name" =>  "music"));
array_push($share, array("name" =>  "networking"));
array_push($share, array("name" =>  "self-development"));
array_push($share, array("name" =>  "networking"));
array_push($share, array("name" =>  "other"));
$form["share"] = $share;
?>
